# 将模型打进镜像里边


# Use the official sglang image
FROM lmsysorg/sglang:v0.4.8.post1-cu126

# Install libgl for opencv support & Noto fonts for Chinese characters
RUN apt-get update && \
    apt-get install -y \
        fonts-noto-core \
        fonts-noto-cjk \
        fontconfig \
        libgl1 && \
    fc-cache -fv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install mineru latest
RUN python3 -m pip install -U 'mineru[all]' -i https://mirrors.aliyun.com/pypi/simple --break-system-packages && \
    python3 -m pip cache purge

# Download models and update the configuration file
RUN /bin/bash -c "mineru-models-download -s modelscope -m all"

# Set the entry point to activate the virtual environment and run the command line tool
ENTRYPOINT ["/bin/bash", "-c", "export MINERU_MODEL_SOURCE=local && exec \"$@\"", "--"]


# docker run -itd \
#   --name mineru \
#   --gpus all \
#   --shm-size 32g \
#   -p 30000:30000 -p 7860:7860 -p 8001:8000 \
#   --ipc=host \
#   mineru-sglang:20250720 \
#   /bin/bash

# # 使用 pipeline/vlm-transformers/vlm-sglang-client 后端
# mineru-gradio --server-name 0.0.0.0 --server-port 7860
# # 或使用 vlm-sglang-engine/pipeline 后端（需安装sglang环境）
# mineru-gradio --server-name 0.0.0.0 --server-port 7860 --enable-sglang-engine true

# # 启动sglang server(需要安装sglang环境)
# mineru-sglang-server --port 30000

# mineru-api --host 0.0.0.0 --port 80009